[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests_new"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "-v --tb=short"
log_cli = true
log_cli_level = "DEBUG"

[tool.pytest-asyncio]
default_scope = "function"
