sources:
  - url: "https://news.binance.com/feed"
    lang: en
    weight: 0.3
  - url: "https://api.cryptopanic.com/v1/posts"
    lang: en
    weight: 0.25
  - url: "https://api.coindesk.com/v1/news"
    lang: en
    weight: 0.2
  - url: "https://api.cointelegraph.com/v1/news"
    lang: en
    weight: 0.15
  - url: "https://api.theblockcrypto.com/v1/posts"
    lang: en
    weight: 0.15
  - url: "https://api.decrypt.co/v1/articles"
    lang: en
    weight: 0.12
  - url: "https://api.bitcoinmagazine.com/v1/articles"
    lang: en
    weight: 0.1
  - url: "https://api.coinjournal.net/v1/news"
    lang: en
    weight: 0.1
  - url: "https://api.cryptoslate.com/v1/news"
    lang: en
    weight: 0.1
  - url: "https://api.cryptobriefing.com/v1/news"
    lang: en
    weight: 0.1
  - url: "https://api.bitcoinist.com/v1/posts"
    lang: en
    weight: 0.1
  - url: "https://api.newsbtc.com/v1/posts"
    lang: en
    weight: 0.1

model_params:
  finbert:
    repo: "ProsusAI/finbert"
    batch_size: 8
    threshold: 0.7
    cache_dir: "./model_cache"
    device: "mps"  # Pour M1/M4

impact_thresholds:
  high: 0.8
  medium: 0.5
  low: 0.3

telegram:
  alert_threshold: 0.7
  update_interval: 300  # 5 minutes
