telegram:
  enabled: true
  token: "VOTRE_TOKEN"
  chat_id: "VOTRE_CHAT_ID"
  notifications:
    trades: true
    market_updates: true
    risk_alerts: true
    performance_updates: true
  alert_intervals:
    market: 3600  # secondes
    performance: 86400  # quotidien
